Feature/add attendee
markuspoerschke/iCal pull request #333
Opened 2021-10-09 21:53 UTC by giorginogreg

As the title.
This closes issue #190

2021-10-11 09:03 UTC, markuspoerschke requested changes
Thanks for your PR. Please have a look at my comments.

2021-10-11 09:03 UTC, markuspoerschke commented on .vscode/settings.json
> +{
Please remove this file, since it is added to `.gitignore`.

2021-10-11 09:03 UTC, markuspoerschke commented on src/Domain/Entity/Event.php
> +    private array $attendee = [];
For arrays, the plural should be used, because more than a single attendee can be added.

```suggestion
    private array $attendees = [];
```

2021-10-11 09:03 UTC, markuspoerschke commented on src/Presentation/Factory/EventFactory.php
> +     *  @SuppressWarnings(PHPMD.NPathComplexity)
Can you create a new `AttendeeFactory` class instead, to reduce the complexity of the `EventFactory` class?

2021-10-11 09:03 UTC, markuspoerschke commented on src/Domain/Entity/Event.php
> +    }
I think we should provide a `setAttendees(array $attendees): self;` method as well.

2021-10-11 09:03 UTC, markuspoerschke commented on CHANGELOG.md
> +-   Event STATUS and METHOD property [#300](https://github.com/markuspoerschke/iCal/pull/300)
Please check the Changelog again. The mentioned Status and Method PR was not yet merged. Please add an entry to the *Unreleased* section.

2021-10-11 09:03 UTC, markuspoerschke commented on src/Domain/Enum/CalendarUserType.php
> +final class CalendarUserType
This should be a real ENUM.

I will check your question here https://github.com/markuspoerschke/iCal/issues/190#issuecomment-938404275 later.

2021-10-11 09:03 UTC, markuspoerschke commented on src/Domain/ValueObject/Attendee.php
> +    private array $delFrom = [];
Please do not user abbreviations in the domain namespace. What does "del" stand for?

2021-10-11 09:03 UTC, markuspoerschke commented on src/Domain/ValueObject/Member.php
> +class Member
```suggestion
final class Member
```

2021-10-11 09:03 UTC, markuspoerschke commented on src/Presentation/Component/Property/Value/QuotedUriValue.php
> +class QuotedUriValue extends UriValue
What is the purpose of having the `QuotedUriValue` class in comparision to the `UriValue` class?

2021-10-13 18:58 UTC, giorginogreg commented on .vscode/settings.json
> +{
Fixed in commit #54ad96b

2021-10-13 18:58 UTC, giorginogreg commented on src/Domain/Entity/Event.php
> +    private array $attendee = [];
Fixed in commit #54ad96b

2021-10-13 18:58 UTC, giorginogreg commented on src/Domain/Entity/Event.php
> +    }
Fixed in commit #54ad96b, please check it again and then you can resolve yourself the conversation, thanks 😁

2021-10-13 18:58 UTC, giorginogreg commented on CHANGELOG.md
> +-   Event STATUS and METHOD property [#300](https://github.com/markuspoerschke/iCal/pull/300)
Fixed in commit #54ad96b, please check it again and then you can resolve yourself the conversation, thanks 😁

2021-10-13 19:00 UTC, giorginogreg commented on src/Domain/ValueObject/Attendee.php
> +    private array $delFrom = [];
Fixed in commit #54ad96b, please check it again and then you can resolve yourself the conversation, thanks 😁

2021-10-13 19:00 UTC, giorginogreg commented on src/Domain/ValueObject/Member.php
> +class Member
Fixed in commit #54ad96b

2021-10-13 19:05 UTC, giorginogreg commented on src/Presentation/Component/Property/Value/QuotedUriValue.php
> +class QuotedUriValue extends UriValue
Dear Markus,
i've done this class so we can have an uri returned with double quotes around it, as more and more RFC commas 
 requires it. 
For example, you can check [this comma](https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.4).
So, for that, i've though to implement it with a toString that return the uri value with double quotes.
Do you think that i could do better? If so, can you give me some hints please?

Thank you 😄

2021-10-13 19:08 UTC, giorginogreg commented on src/Domain/Enum/CalendarUserType.php
> +final class CalendarUserType
@markuspoerschke haven't had no more reply to my question/s, do you have some suggestions of how we can implement this enum?

2021-10-13 19:31 UTC, giorginogreg commented on src/Presentation/Factory/EventFactory.php
> +     *  @SuppressWarnings(PHPMD.NPathComplexity)
Created in #0f27074. Please check it asap, then if it's ok for you, you can mark this question as solved, Thank you 😃

2021-10-29 21:33 UTC, markuspoerschke commented on src/Domain/Enum/CalendarUserType.php
> +final class CalendarUserType
Exactly as you stated in the screenshots. I added the Enums to this PR.

2021-10-29 21:36 UTC, markuspoerschke commented
Thanks for this feature!

2021-10-29 21:36 UTC, merged